ecom/cartapp/urls.py
from django.urls import path
from .import views
app_name='cartapp'


urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('del/<int:product_id>/',views.del_cart,name='del_cart'),
    path('remove/<int:product_id>/', views.remove, name='remove')

]

ecom/ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopapp/',include('shopapp.urls')),
    path('search/', include('searchapp.urls')),
    path('cartapp/',include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                       document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                       document_root=settings.MEDIA_ROOT)

ecom/searchapp/urls.py
from django.urls import path
from .import views

app_name='searchapp'

urlpatterns=[
    path('',views.Searchresult,name='Searchresult'),
]

ecom/shopapp/urls.py
from django.urls import path
from shopapp import views
app_name='shopapp'
urlpatterns = [

    path('',views.allprodcat,name='allprodcat'),
    path('<slug:c_slug>/',views.allprodcat,name='products_by_category'),
path('<slug:c_slug>/<slug:product_slug>/',views.prodetail,name='productcategory')
]

ecom/cartapp/models.py
from django.db import models
from shopapp.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}' .format(self.cart_id)

class Cartitem(models.Model):

    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='Cartitem'
    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecom/shopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    img=models.ImageField(upload_to='catagory',blank=True)
    slug=models.SlugField(max_length=250,unique=True)



    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'



    def __str__(self):
        return self.name

    def get_url(self):
        return reverse('shopapp:products_by_category',args=[self.slug])

class Product(models.Model):
    objects = None
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    mfd=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now=True)


    def get_url(self):
        return reverse('shopapp:productcategory', args=[self.category.slug,self.slug])


    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}' .format(self.name)

ecom/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopapp.models import Product
from .models import Cart,Cartitem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),

    try:
        cart_item=Cartitem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except Cartitem.DoesNotExist:
        cart_item=Cartitem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cartapp:cart_detail')


def del_cart(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=Cartitem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:cart_detail')


def remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cartitem.objects.get(product=product, cart=cart)
    cart_item.delete()

    return redirect('cartapp:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = Cartitem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items,total=total,counter=counter))

ecom/searchapp/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q
# Create your views here.


def Searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter( Q(name__contains=query) | Q(desc__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecom/shopapp/views.py
# from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator,InvalidPage,EmptyPage
from . models import category,Product
# Create your views here.
# def index(request):
#     return HttpResponse("haloo")



def allprodcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug != None:
        c_page=get_object_or_404(category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True )
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})


def prodetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'Product':product })

    

ecom/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >-->

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div >
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
    {% endblock %}
  </div>

{% include 'footer.html' %}

<script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</div>

</body>
</html>

ecom/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
CART PAGE HERE


Here are your search results

{% endblock %}
{% block title %}
cart ALUSHOP
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Shopping cart is empty
        </h1>
        <br>
        <p class="text-center">
            Pleace click <a href="{% url 'shopapp:allprodcat' %}">Here</a>to continue shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_coustom_table">
        <thead class="my_custom_thead">
        <tr>
            <th colspan="5">
                Your Items
            </th>
        </tr>
        </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.img.url}}" style="width:100px ; height:100px" alt="" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-lef">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price: rs {{cart_item.product.price}}
                    <br>
                    Qty : {{cart_item.quantity}} x $ {{cart_item}}

                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a" ><i class="fa fa-plus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:del_cart' cart_item.product.id %}" class="custom_a" ><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:remove' cart_item.product.id %}" class="custom_icon" ><i class="fa fa-trash custom_icon" ></i></a>
                </td>
                {% else %}
                   <td>

                    &nbsp;<a href="{% url 'cartapp:del_cart' cart_item.product.id %}" class="custom_a" ><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:remove' cart_item.product.id %}" class="custom_icon" ><i class="fa fa-trash custom_icon" ></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>
            Checkout
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="text-center">
                Please cross check
            </td>
        </tr>
        <tr>
            <td class="text-center">
                your total is :<strong> {{total}}</strong>

            </td>
        </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'shopapp:allprodcat' %} " class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
    </div>
</div>
</div>
{% endif %}
{% endblock %}

ecom/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
{{ category.description |truncatewords:155}}
{% else %}
welcome to alu shop
{% endif %}
{% endblock %}
{% block title %}
 {% if category %}
        {{category.name }} --alu store

    {% else %}
         producs....

 {% endif %}

{% endblock %}

{% block content %}
 {% if category %}

      <div>
          <div class="row rowclass">

          <div class="mx-auto">
              <p><a href="{% url 'shopapp:allprodcat' %}"> our products </a></p>
          </div>
          </div>
      </div>
 {% endif %}
<div class="mx-auto">
    {% if category %}
    <img  src="{{category.img.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1 class="text-center my-title">{{category.name}}</h1>
    <p class="justify">
        {{category.description}}
    </p>
</div>
{% else %}
<div>
 <img class="myimg1 " src ="{% static 'img/banner.png' %}" alt="our products">
</div>
<br>
<div>
    <h1 class="text-center my-title">our products collections</h1>
    <p class="justify">
        You can click on the ‘item to generate’ column and select the format you want content in.

Below that, you can select if you want an HTML tag in your content or not

After that, you can choose how many paragraphs you want in the ‘how many items to generate’ column.

Then, you can choose the minimum and maximum words you want per sentence.

Later, you can select the minimum and maximum sentences you want per paragraph.

Finally, click on the button ‘generate’

Taddalaa!

You got your Lorem Ipsum content for your website.
    </p>
</div>
 {% endif %}
<div class="container">
    <div class="row mx-auto">

        {% for product in products.object_list %}

        <div class="my-bottom-margin col-9 col-sm-12 col-md-4 xol-lg-4 ">
<div class=" h-100 card shadow-lg p-3 mb-5 bg-white rounded" style="width:23rem;">

                <a href="{{product.get_url}}"><img class="card-img-top myimg imgp" src="{{product.img.url}}" alt="<<product.name}}"></a>
             <div class="card-body">

                    <h4 class="card-title pname">{{ product.name }}</h4>
                    <p class="card-subtitle my-title">{{ product.price }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

<hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
        </div>
            {% endif %}

    </div>
    <br>
</div>
<!--<div class="container">-->
<!--  <div class="card-columns">-->

<!--    <div class="card">-->
<!--      <div class="card-header">-->
<!--        Card Header-->
<!--      </div>-->
<!--      <img class="card-img-top" src="https://source.unsplash.com/daily" alt="Card image top">-->
<!--      <div class="card-body">-->
<!--        <h3 class="card-title">Each Card body can have a title</h3>-->
<!--        <h4 class="card-subtitle">And a subtitle</h4>-->
<!--        <p class="card-text">This is a card body 1</p>-->
<!--      </div>-->
{% endblock %}

ecom/templates/footer.html
<div class=" footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; alu is the man</p>
</div>

ecom/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shopapp:allprodcat' %}"></a>
        <div class="imga">
        <img src="{% static 'img/logo.png' %}"  alt="logimage" width="150px" height="150px">
        </div>
    </center>
</header>

ecom/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">

  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'shopapp:allprodcat' %}">ALU SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-togg ler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Product List
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shopapp:allprodcat' %}">All Products</a></li>
             {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{ cat.name }}</a></li>
            {% endfor %}


          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'cartapp:cart_detail' %}"><i  class="fa fa-shopping-cart" ></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchapp:Searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecom/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.description|truncatewords:155 }}





{% endblock %}
{% block title %}
 {% if category %}
        {{product.name }} --alu store


 {% endif %}

{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p> <a href="{% url 'shopapp:allprodcat' %}" >HOME</a> | <a href="{{Product.category.get_url}}">{{Product.category}}</a> | {{Product.name}}</p>
    </div>

<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img  class="myimg2" src="{{Product.img.url}}" alt="{{Product.name}}">

        </div>
    </div>


        <div class="co l-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="pname">{{Product.name}}</h1>
            <p class="my-title">${{Product.price}}</p>
           <p class="pdsc">Product Description</p>
            <p class="desc">{{Product.desc}}</p>
            {% if Prodcut.stock <= 0  %}
            <p><b>Out of Stock</b></p>
            {% else %}
            <div class="pname">
            <a class="btn btn-secondary" href="{% url 'cartapp:add_cart' Product.id %}">ADD to Cart</a>

            </div>
            {% endif %}
            </div>
        </div>

</div>
</div>
</div>
{% endblock %}

ecom/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}




Here are your search results

{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center mysearch">You have searched for :<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx-auto">

        {% for product in products %}

        <div class="my-bottom-margin col-9 col-sm-12 col-md-4 xol-lg-4 ">
<div class=" h-100 card shadow-lg p-3 mb-5 bg-white rounded" style="width:23rem;">

                <a href="{{product.get_url}}"><img class="card-img-top myimg imgp" src="{{product.img.url}}" alt="<<product.name}}"></a>
             <div class="card-body">

                    <h4 class="card-title pname">{{ product.name }}</h4>
                    <p class="card-subtitle my-title">{{ product.price }}</p>
                </div>
            </div>
        </div>



{% empty %}
<div class="row mx-auto">
    <p class="text-center mysearch">0 results</p>
</div>

{% endfor %}
     </div>
    </div>
{% endblock %}