todo/todo/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from todo import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                       document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                       document_root=settings.MEDIA_ROOT)

todo/todoapp/urls.py
from django.urls import path, include
from . import views
app_name = 'taskapp'
urlpatterns = [

    path('',views.home,name='home'),
    # path('detail',views.detail,name="detail")
    path('del/<int:taskid>/',views.delete,name='delete'),
    path('edit/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.classviews.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.classdetail.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.classupdate.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.classdelete.as_view(),name='cbvdelete')
]

todo/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    objects = None
    task=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()


    def __str__(self):
        return self.task

todo/todoapp/forms.py
from django import forms
from .models import Task

class todoform(forms.ModelForm):
    class Meta:
        model= Task
        fields=['task','priority','date']

todo/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from .forms import todoform
from .models import Task
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.views.generic import DeleteView


class classviews(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task'


class classdetail(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'


class classupdate(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ['task','priority','date']

    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})

class classdelete(DeleteView):
    model = Task
    template_name = 'del.html'
    success_url = reverse_lazy('cbvhome')
# Create your views here.
def home(request):
    task1 = Task.objects.all()
    if request.method == "POST":
        task1 = request.POST.get('task1','')
        prior = request.POST.get('prior1','')
        date1 = request.POST.get('date1','')
        task = Task(task=task1, priority=prior, date=date1)
        task.save()
    return render(request, 'home.html', {'task': task1})


# def detail(request):
#     task=Task.objects.all()
#     return render(request,'detail.html',{'task':task1})


def delete(request,taskid,):
    if request.method=="POST":
        task=Task.objects.get(id=taskid)
        task.delete()
        return redirect('/')
    return render(request,'del.html')

def update(request,id):
    task = Task.objects.get(id=id)
    form1 = todoform(request.POST or None, instance=task)
    if form1.is_valid():
        form1.save()
        return redirect('/')
    return render(request, 'edit.html', {'task': task, 'form': form1})

todo/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
{% block body%}
{% endblock %}
</body>
</html>

todo/templates/del.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
<p> are u sure </p>
    <input type="submit">
</form>
{% endblock %}

todo/templates/detail.html
{% extends 'base.html' %}
{% block body %}

  <div class="card-body">
    <h5 class="Card title">{{task.task}}</h5>
    <p class="card-text">{{task.priority}}</p>
      <p class="card-text">{{task.date}}</p>

    <a href="{% url 'delete' task.id %}" class="btn btn-primary">Done</a>
      <a href="{% url 'update' task.id %}" class="btn btn-primary">Edit</a>
  </div>
{% endblock %}

todo/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" >
{% csrf_token %}
  {{ form.as_p }}
   <button type="submit" >Update</button>
</form>
{% endblock %}

todo/templates/home.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>TODO</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container" >
    <div class="row">
<div class="col-md-6">
<form method="post" class="p-3 shadow">
    <h1> Add Task</h1>
    {% csrf_token %}
  <div class="form-group">
    <label >TASK</label>
    <input type="text" class="form-control"  name="task1" placeholder="Enter the Task">

  </div>
  <div class="form-group">
    <label >PRIORITY</label>
    <input type="text" class="form-control" name="prior1" placeholder="Enter the Priority">
  </div>
     <div class="form-group">
    <label >DATE</label>
    <input type="date" class="form-control" name="date1" placeholder="Input the date">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>




    </div>

        <div class="col-md-6">
            <h1>Task to be completed</h1>
             {% for i in task %}
             <div class="shadow card" >

  <div class="card-body">
    <h5 class="Card title">{{i.task}}</h5>
    <p class="card-text">{{i.priority}}</p>
      <p class="card-text">{{i.date}}</p>

    <a href="{% url 'taskapp:delete' i.id %}" class="btn btn-primary">Done</a>
      <a href="{% url 'taskapp:update' i.id %}" class="btn btn-primary">Edit</a>
  </div>
        </div><br>
             {% endfor %}
</div>


</div>
</div>
{% endblock %}

todo/templates/update.html
{% extends 'base.html' %}
{% block body %}

<div class="card">
  <div class="class-header">
    <div class="class-title">
      Update
    </div>
    <div class="class-body">
      <form method="post" >
{% csrf_token %}
  {{ form.as_p }}
  <button type="submit" >Update</button>
</form>
    </div>
  </div>
</div>

{% endblock %}